### ISSUE TITLE
[Android Bootcamp] Project 2: Google Grid Image Search Ready for Review

### ISSUE THREAD

**Issue by skipit** [skipit/GridImageSearch#1]
/cc @codepathreview @codepath
Completed all the required stories and a few of the Advanced Stories. The Application is ready for review.

Will continue to work on other aspects as feasible.

**Comment by codepathreview** [comment]
:+1: Nice work overall !!! A few notes after checking out the code:
- Good to see you used a filters object to represent the filters to apply to the query
- Good job using StaggeredGridView and TouchImageView for enhancing UI/UX
- Consider using Parcelable instead of Serializable ([benefits](http://stackoverflow.com/a/5551155)) for SearchResult
- Consider adding error checks / check for internet connectivity, etc
- Great job implementing DialogFragment for filter settings
- Good to see you added Search using the action bar and correctly implemented sharing 
- Good to see JSON deserializing logic in the Image object. (Consider adding null checks)

Also, here's a more detailed [Project 2 Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](https://gist.github.com/nesquena/44091e4727b154d04269) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
